# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).



# Import Numpy and converting Python arrays to Numpy Arrays

In [7]:

import numpy as np 
li= [1,2,3]
arr= np.array(li)
print(arr)


[1 2 3]


In [8]:
arr

array([1, 2, 3])

# For 2-D arrays


In [9]:
arr2 = [[1,2,3],[4,6,7],[3,4,5]]
print(arr2)

[[1, 2, 3], [4, 6, 7], [3, 4, 5]]


In [10]:
np.array(arr2)


array([[1, 2, 3],
       [4, 6, 7],
       [3, 4, 5]])

# using Numpy arange function

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

# Initializing arrays of zeroes using zero function 

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# using ones function for initializing array with one

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

# using linspace function to generate array elements with equal spaces

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

# using eye functions to generate identity matrix of n rows and col

In [17]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# using reshape function to change the shape of array

In [18]:
arr = np.arange(0,25)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
randarr = np.random.randint(0,50,10)

In [22]:
randarr

array([28, 23, 47, 28, 47, 40,  9, 26,  3, 33])

In [23]:
randarr.max()

47

In [24]:
randarr.argmax()

2

# Numpy Array indexing  and selection


In [25]:
arr = np.arange(0,11)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# use list slicing for getting element according to need  and use copy method to create copy.

In [27]:
arr_copy = arr.copy()

In [29]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
bool_Arr = arr > 5

In [31]:
bool_Arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [32]:
arr[bool_Arr]

array([ 6,  7,  8,  9, 10])